# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import async_call_pb2 as async__call__pb2


class DuckServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Quack = channel.unary_unary(
                '/asynch.DuckService/Quack',
                request_serializer=async__call__pb2.QuackRequest.SerializeToString,
                response_deserializer=async__call__pb2.QuackResponse.FromString,
                )


class DuckServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Quack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DuckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Quack': grpc.unary_unary_rpc_method_handler(
                    servicer.Quack,
                    request_deserializer=async__call__pb2.QuackRequest.FromString,
                    response_serializer=async__call__pb2.QuackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asynch.DuckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DuckService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Quack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/asynch.DuckService/Quack',
            async__call__pb2.QuackRequest.SerializeToString,
            async__call__pb2.QuackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
