# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: async_call.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='async_call.proto',
  package='asynch',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x61sync_call.proto\x12\x06\x61synch\"\"\n\x0cQuackRequest\x12\x12\n\nquackTimes\x18\x01 \x01(\x05\"!\n\rQuackResponse\x12\x10\n\x08quackMsg\x18\x01 \x01(\t2C\n\x0b\x44uckService\x12\x34\n\x05Quack\x12\x14.asynch.QuackRequest\x1a\x15.asynch.QuackResponseb\x06proto3'
)




_QUACKREQUEST = _descriptor.Descriptor(
  name='QuackRequest',
  full_name='asynch.QuackRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='quackTimes', full_name='asynch.QuackRequest.quackTimes', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=62,
)


_QUACKRESPONSE = _descriptor.Descriptor(
  name='QuackResponse',
  full_name='asynch.QuackResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='quackMsg', full_name='asynch.QuackResponse.quackMsg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['QuackRequest'] = _QUACKREQUEST
DESCRIPTOR.message_types_by_name['QuackResponse'] = _QUACKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuackRequest = _reflection.GeneratedProtocolMessageType('QuackRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUACKREQUEST,
  '__module__' : 'async_call_pb2'
  # @@protoc_insertion_point(class_scope:asynch.QuackRequest)
  })
_sym_db.RegisterMessage(QuackRequest)

QuackResponse = _reflection.GeneratedProtocolMessageType('QuackResponse', (_message.Message,), {
  'DESCRIPTOR' : _QUACKRESPONSE,
  '__module__' : 'async_call_pb2'
  # @@protoc_insertion_point(class_scope:asynch.QuackResponse)
  })
_sym_db.RegisterMessage(QuackResponse)



_DUCKSERVICE = _descriptor.ServiceDescriptor(
  name='DuckService',
  full_name='asynch.DuckService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=99,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='Quack',
    full_name='asynch.DuckService.Quack',
    index=0,
    containing_service=None,
    input_type=_QUACKREQUEST,
    output_type=_QUACKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DUCKSERVICE)

DESCRIPTOR.services_by_name['DuckService'] = _DUCKSERVICE

# @@protoc_insertion_point(module_scope)
